# Test our SVD implementation

In [9]:
import numpy as np
from SVD import SVD
from sklearn.decomposition import TruncatedSVD

#Create a random matrix A
np.random.seed(42)
A = np.random.rand(6, 4)  # 6x4 matrix

# Specify the number of components
n_components = 3

# Compute the SVD
svd = SVD(A, n_components)

# Get the decomposition
V, sigma = svd.get_decomposition()

# Print the results
print("Matrix A:")
print(A)
print("\nMatrix V (reduced to n_components):")
print(V)
print("\nMatrix Sigma (reduced to n_components):")
print(sigma)

svd = TruncatedSVD(n_components=2)
X_svd = svd.fit_transform(A)
print("\nMatrix V (reduced to n_components):")
print(svd.components_)

This is Q:
 [[-0.48768129  0.08999469  0.86163116 -0.10797985]
 [-0.52514948 -0.52813508 -0.16091271  0.64760981]
 [ 0.56418903 -0.72649579  0.39045433 -0.03794766]
 [ 0.4099704   0.43032332  0.28150356  0.7533272 ]]
This is A:
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed